// Shared look for the Add Order and Edit Order pages (style objects keyed the
// same way both pages already use them, so no page logic changes).

const C = {
  bg: "#f3f5f9",
  surface: "#ffffff",
  border: "#e3e8ef",
  borderStrong: "#cfd7e2",
  text: "#0f172a",
  text2: "#334155",
  muted: "#64748b",
  faint: "#94a3b8",
  primary: "#2563eb",
  primaryDark: "#1d4ed8",
  primarySoft: "#eff6ff",
  danger: "#dc2626",
  dangerSoft: "#fef2f2",
  success: "#059669",
  readonly: "#f5f7fa",
};

export const ORDER_COLORS = C;

// Delay fields: negative = early (green), positive = late (red), 0/empty = neutral.
export const delayColor = (value) => {
  const n = Number(value);
  if (value === "" || value === null || value === undefined || Number.isNaN(n) || n === 0) {
    return C.text2;
  }
  return n < 0 ? C.success : C.danger;
};

const field = {
  width: "100%",
  height: "40px",
  padding: "0 12px",
  border: `1px solid ${C.borderStrong}`,
  borderRadius: "9px",
  fontSize: "14px",
  outline: "none",
  fontFamily: "inherit",
  background: C.surface,
  color: C.text,
  boxSizing: "border-box",
  transition: "border-color 0.15s, box-shadow 0.15s",
};

const btn = {
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  gap: "8px",
  height: "40px",
  padding: "0 18px",
  borderRadius: "10px",
  fontWeight: 600,
  fontSize: "14px",
  cursor: "pointer",
  whiteSpace: "nowrap",
  fontFamily: "inherit",
};

export const orderFormStyles = {
  appContainer: {
    display: "flex",
    background: C.bg,
    fontFamily: "'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif",
    height: "100vh",
    overflow: "hidden",
  },
  mainContent: { flex: 1, minWidth: 0, padding: "0 28px 24px", overflowY: "auto", height: "100vh" },
  addOrderContainer: { maxWidth: "1320px", margin: "0 auto" },
  editOrderContainer: { maxWidth: "1320px", margin: "0 auto" },

  pageHeader: {
    position: "sticky",
    top: 0,
    zIndex: 20,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "16px",
    padding: "20px 0 16px",
    marginBottom: "8px",
    background: "rgba(243, 245, 249, 0.94)",
    backdropFilter: "blur(6px)",
    borderBottom: `1px solid ${C.border}`,
  },
  headerLeft: { display: "flex", alignItems: "center", gap: "14px", minWidth: 0 },
  headerActions: { display: "flex", gap: "10px", flexWrap: "wrap" },
  backButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "40px",
    height: "40px",
    flexShrink: 0,
    borderRadius: "10px",
    border: `1px solid ${C.borderStrong}`,
    background: C.surface,
    cursor: "pointer",
    color: C.text2,
    boxShadow: "0 1px 2px rgba(15,23,42,0.05)",
  },
  pageTitle: {
    fontSize: "22px",
    fontWeight: 700,
    color: C.text,
    margin: 0,
    marginBottom: "2px",
    letterSpacing: "-0.02em",
  },
  pageSubtitle: { fontSize: "13px", color: C.muted, margin: 0 },
  btnPrimary: {
    ...btn,
    border: "none",
    background: `linear-gradient(135deg, #3b82f6 0%, ${C.primaryDark} 100%)`,
    color: "#fff",
    boxShadow: "0 4px 12px rgba(37, 99, 235, 0.28)",
  },
  btnCancel: {
    ...btn,
    border: `1px solid ${C.borderStrong}`,
    background: C.surface,
    color: C.text2,
  },

  statusBadge: {
    display: "inline-flex",
    alignItems: "center",
    height: "28px",
    padding: "0 12px",
    borderRadius: "999px",
    fontSize: "12.5px",
    fontWeight: 600,
    margin: "8px 0 16px",
    border: "1px solid transparent",
  },
  running: { background: "#ecfdf5", color: "#047857", borderColor: "#a7f3d0" },
  shipped: { background: "#eff6ff", color: "#1d4ed8", borderColor: "#bfdbfe" },
  active: { background: "#eff6ff", color: "#1d4ed8", borderColor: "#bfdbfe" },
  pending: { background: "#fffbeb", color: "#b45309", borderColor: "#fde68a" },
  cancelled: { background: "#fef2f2", color: "#b91c1c", borderColor: "#fecaca" },

  // The form is a column of section cards
  formCard: { background: "transparent", border: "none", marginTop: "8px" },
  formContent: { padding: 0 },
  formActions: {
    position: "sticky",
    bottom: 0,
    zIndex: 15,
    display: "flex",
    justifyContent: "flex-end",
    gap: "12px",
    padding: "14px 20px",
    marginTop: "4px",
    background: "rgba(255, 255, 255, 0.96)",
    backdropFilter: "blur(6px)",
    border: `1px solid ${C.border}`,
    borderRadius: "14px",
    boxShadow: "0 -6px 20px rgba(15, 23, 42, 0.06)",
  },
  section: {
    background: C.surface,
    border: `1px solid ${C.border}`,
    borderRadius: "14px",
    boxShadow: "0 1px 2px rgba(15,23,42,0.04), 0 1px 3px rgba(15,23,42,0.03)",
    paddingBottom: "22px",
    marginBottom: "16px",
  },
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "14px 22px",
    marginBottom: "20px",
    borderBottom: `1px solid ${C.border}`,
    background: "linear-gradient(180deg, #fbfcfe 0%, #ffffff 100%)",
    borderRadius: "14px 14px 0 0",
  },
  sectionIcon: {
    width: "34px",
    height: "34px",
    padding: "9px",
    flexShrink: 0,
    borderRadius: "10px",
    background: C.primarySoft,
    color: C.primary,
    boxSizing: "border-box",
  },
  sectionTitle: {
    fontSize: "16px",
    fontWeight: 600,
    color: C.text,
    margin: 0,
    letterSpacing: "-0.01em",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))",
    gap: "18px 20px",
    padding: "0 22px",
  },
  formField: { display: "flex", flexDirection: "column", minWidth: 0 },
  formFieldFull: { display: "flex", flexDirection: "column", gridColumn: "1 / -1" },
  formLabel: {
    fontSize: "12.5px",
    fontWeight: 600,
    color: C.text2,
    marginBottom: "6px",
  },
  required: { color: C.danger, marginLeft: "2px" },
  input: { ...field },
  select: { ...field, cursor: "pointer" },
  textarea: { ...field, height: "auto", minHeight: "84px", padding: "10px 12px", resize: "vertical", lineHeight: 1.5 },
  readonlyInput: { background: C.readonly, color: C.text2, cursor: "not-allowed" },

  loadingState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "60vh",
    textAlign: "center",
  },
  spinner: {
    width: "36px",
    height: "36px",
    border: "3px solid #dbeafe",
    borderTopColor: C.primary,
    borderRadius: "50%",
    animation: "spin 0.8s linear infinite",
    marginBottom: "16px",
  },
  loadingText: { fontSize: "12px", color: C.muted, marginTop: "4px" },

  snackbar: {
    position: "fixed",
    bottom: "24px",
    right: "24px",
    padding: "12px 18px",
    borderRadius: "12px",
    color: "#fff",
    fontSize: "14px",
    fontWeight: 500,
    display: "flex",
    alignItems: "center",
    gap: "12px",
    zIndex: 1000,
    boxShadow: "0 10px 30px rgba(15, 23, 42, 0.25)",
  },
  snackbarClose: {
    background: "none",
    border: "none",
    color: "#fff",
    fontSize: "20px",
    cursor: "pointer",
    padding: "0 4px",
    lineHeight: 1,
  },

  addButton: {
    ...btn,
    height: "34px",
    padding: "0 14px",
    fontSize: "13px",
    border: "none",
    background: C.primary,
    color: "#fff",
    marginLeft: "auto",
  },
  removeButton: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    height: "30px",
    padding: "0 10px",
    background: C.dangerSoft,
    color: C.danger,
    border: "1px solid #fecaca",
    borderRadius: "8px",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
  },

  tableWrapper: {
    overflowX: "auto",
    margin: "20px 22px 0",
    border: `1px solid ${C.border}`,
    borderRadius: "12px",
  },
  colorSizeTable: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "13px",
    fontVariantNumeric: "tabular-nums",
  },
  tableHeader: {
    padding: "10px 12px",
    textAlign: "center",
    background: "#f1f5f9",
    borderBottom: `1px solid ${C.borderStrong}`,
    fontWeight: 700,
    fontSize: "11.5px",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    color: C.text2,
    whiteSpace: "nowrap",
  },
  tableCell: { padding: "8px 10px", textAlign: "center", borderBottom: `1px solid ${C.border}` },
  tableFooter: {
    padding: "10px 12px",
    textAlign: "center",
    background: "#eaf0fb",
    borderTop: `1px solid ${C.borderStrong}`,
    fontWeight: 700,
    color: C.text,
  },
  colorInput: { ...field, width: "140px", height: "34px", fontSize: "13px" },
  quantityInput: { ...field, width: "76px", height: "34px", fontSize: "13px", textAlign: "center", padding: "0 6px" },
  totalInput: {
    ...field,
    width: "86px",
    height: "34px",
    fontSize: "13px",
    textAlign: "center",
    padding: "0 6px",
    background: C.readonly,
    fontWeight: 700,
  },
  emptyState: {
    textAlign: "center",
    padding: "32px",
    color: C.muted,
    background: "#f8fafc",
    border: `1px dashed ${C.borderStrong}`,
    borderRadius: "12px",
    margin: "16px 22px 0",
  },

  filesUploadSection: { padding: "0 22px", display: "grid", gap: "16px" },
  uploadArea: {
    padding: "18px",
    background: "#f8fafc",
    borderRadius: "12px",
    border: `1.5px dashed ${C.borderStrong}`,
    transition: "all 0.2s",
  },
  uploadAreaDragging: { borderColor: C.primary, background: C.primarySoft },
  uploadLabel: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "14px",
    fontWeight: 600,
    color: C.text,
    marginBottom: "8px",
  },
  dropZone: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "18px",
    textAlign: "center",
    color: C.muted,
    fontSize: "13px",
  },
  dropZoneIcon: { fontSize: "36px", color: C.faint, marginBottom: "6px" },
  browseButton: {
    display: "inline-flex",
    alignItems: "center",
    height: "34px",
    padding: "0 16px",
    background: C.surface,
    color: C.primary,
    border: "1px solid #bfdbfe",
    borderRadius: "9px",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
  },
  uploadingIndicator: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "10px 12px",
    background: C.primarySoft,
    borderRadius: "9px",
    color: C.primary,
    marginTop: "12px",
    fontSize: "13px",
  },
  fileItem: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "10px 14px",
    background: C.surface,
    borderRadius: "10px",
    border: `1px solid ${C.border}`,
    marginTop: "8px",
  },
  imageThumbnail: {
    width: "46px",
    height: "46px",
    flexShrink: 0,
    borderRadius: "8px",
    overflow: "hidden",
    cursor: "pointer",
    background: "#f1f5f9",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  thumbnailImg: { width: "100%", height: "100%", objectFit: "cover" },
  fileIcon: { fontSize: "26px", color: C.muted, flexShrink: 0 },
  fileInfo: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: "2px" },
  fileName: {
    fontSize: "13.5px",
    fontWeight: 600,
    color: C.text,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  fileSize: { fontSize: "11.5px", color: C.faint },
  fileActions: { display: "flex", gap: "6px", flexShrink: 0 },
  renameFileBtn: {
    background: C.primarySoft,
    border: "none",
    color: C.primary,
    cursor: "pointer",
    height: "30px",
    padding: "0 10px",
    borderRadius: "8px",
    fontSize: "12px",
    fontWeight: 600,
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
  },
  removeFileBtn: {
    background: C.dangerSoft,
    border: "none",
    color: C.danger,
    cursor: "pointer",
    height: "30px",
    padding: "0 10px",
    borderRadius: "8px",
    fontSize: "12px",
    fontWeight: 600,
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
  },

  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(15, 23, 42, 0.5)",
    backdropFilter: "blur(2px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modal: {
    background: C.surface,
    borderRadius: "16px",
    width: "90%",
    maxWidth: "480px",
    overflow: "hidden",
    boxShadow: "0 24px 60px rgba(15, 23, 42, 0.3)",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px 20px",
    borderBottom: `1px solid ${C.border}`,
  },
  modalTitle: { fontSize: "16px", fontWeight: 700, color: C.text, margin: 0 },
  modalClose: { background: "none", border: "none", fontSize: "18px", cursor: "pointer", color: C.muted },
  modalBody: { padding: "20px" },
  modalFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "10px",
    padding: "14px 20px",
    borderTop: `1px solid ${C.border}`,
    background: "#fbfcfe",
  },
  modalCancel: { ...btn, height: "36px", border: `1px solid ${C.borderStrong}`, background: C.surface, color: C.text2 },
  modalSubmit: {
    ...btn,
    height: "36px",
    border: "none",
    background: C.primary,
    color: "#fff",
    textDecoration: "none",
  },
  renameSection: { marginBottom: "16px" },
  currentFileName: {
    padding: "10px 12px",
    background: "#f1f5f9",
    borderRadius: "9px",
    fontSize: "13.5px",
    color: C.text2,
    marginTop: "4px",
    wordBreak: "break-all",
  },
  renameInput: { ...field, marginTop: "4px" },
  fileExtensionHint: { fontSize: "12px", color: C.muted, marginTop: "6px" },
  imageViewerModal: {
    background: C.surface,
    borderRadius: "16px",
    width: "90%",
    maxWidth: "900px",
    maxHeight: "90vh",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    boxShadow: "0 24px 60px rgba(15, 23, 42, 0.3)",
  },
  imageViewerHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "14px 20px",
    borderBottom: `1px solid ${C.border}`,
  },
  imageViewerBody: {
    flex: 1,
    padding: "20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "auto",
    background: "#f8fafc",
  },
  fullImage: { maxWidth: "100%", maxHeight: "70vh", objectFit: "contain", borderRadius: "8px" },
  imageViewerFooter: {
    display: "flex",
    justifyContent: "flex-end",
    padding: "14px 20px",
    borderTop: `1px solid ${C.border}`,
  },

  searchableSelectContainer: { position: "relative", width: "100%" },
  searchableSelectInputWrapper: { position: "relative", display: "flex", alignItems: "center" },
  searchIcon: { position: "absolute", left: "12px", color: C.faint, fontSize: "13px", pointerEvents: "none" },
  searchableSelectInput: { ...field, padding: "0 32px 0 34px" },
  clearSelectionBtn: {
    position: "absolute",
    right: "8px",
    background: "none",
    border: "none",
    color: C.faint,
    cursor: "pointer",
    padding: "6px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "6px",
  },
  searchableDropdown: {
    position: "absolute",
    top: "100%",
    left: 0,
    right: 0,
    maxHeight: "300px",
    overflowY: "auto",
    background: C.surface,
    border: `1px solid ${C.border}`,
    borderRadius: "10px",
    boxShadow: "0 16px 32px rgba(15, 23, 42, 0.14)",
    zIndex: 1000,
    marginTop: "6px",
    padding: "4px",
  },
  dropdownLoading: {
    padding: "18px",
    textAlign: "center",
    color: C.muted,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
  },
  dropdownNoResults: { padding: "18px", textAlign: "center", color: C.muted },
  dropdownItem: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "9px 10px",
    cursor: "pointer",
    borderRadius: "8px",
    transition: "background 0.15s",
  },
  dropdownItemSelected: { background: C.primarySoft },
  dropdownItemIcon: { color: C.faint, fontSize: "13px", flexShrink: 0 },
  dropdownItemContent: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column" },
  dropdownItemName: { fontSize: "13.5px", fontWeight: 500, color: C.text },
  dropdownItemId: { fontSize: "11px", color: C.faint },
  dropdownItemCheck: { color: C.primary, fontSize: "13px", flexShrink: 0 },
};

// Hover/focus details that inline styles can't express, scoped to the form
// page (class "ord-form" on the page root).
export const ORDER_FORM_CSS = `
  .ord-form input:focus, .ord-form select:focus, .ord-form textarea:focus {
    border-color: ${C.primary} !important;
    box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.14);
  }
  .ord-form input[readonly], .ord-form input:read-only {
    background: ${C.readonly};
  }
  .ord-form button:disabled { opacity: 0.55; cursor: not-allowed; }
`;
